// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4ffffb6c-cf0a-4512-996c-1ac85f3680db",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_UPdm7hYFR",
    "aws_user_pools_web_client_id": "1fp6k42i5vpeur0pviqiep36cm",
    "aws_mobile_analytics_app_id": "a200ccc82c874139bf48e254e28594f3",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://mugg6juok5ajbgqpcweslf2n4q.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "myhr10-20181128151715--hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://myhr10-20181128151715--hostingbucket.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
